# Generated by Django 4.0.3 on 2022-03-18 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('nome_aluno', models.CharField(max_length=200)),
                ('ra_aluno', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('data_nasc', models.DateField()),
                ('mae_aluno', models.CharField(max_length=200)),
                ('pai_aluno', models.CharField(max_length=200)),
                ('rua_aluno', models.CharField(max_length=200)),
                ('numero_aluno', models.IntegerField(max_length=6)),
                ('bairro_aluno', models.CharField(max_length=100)),
                ('cidade_aluno', models.CharField(max_length=100)),
                ('estado_aluno', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero_aluno', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_materia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_professor', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_1_trim', models.FloatField(default=0)),
                ('nota_2_trim', models.FloatField(default=0)),
                ('nota_3_trim', models.FloatField(default=0)),
                ('nota_4_trim', models.FloatField(default=0)),
                ('relatorio_aluno', models.TextField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicativo.aluno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicativo.materia')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicativo.professor')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='genero_aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicativo.genero'),
        ),
    ]
